// Code generated by hertz generator.

package car

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/jiaojiajun/qq_speed_helper_backend/biz/dal/mysql"
	car "github.com/jiaojiajun/qq_speed_helper_backend/biz/model/helper/car"
)

// GetAllCars .
// @router v1/car/get_all [GET]
func GetAllCars(ctx context.Context, c *app.RequestContext) {
	var err error
	var req car.GetAllCarsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, err := GetAllCarsInner(ctx, c)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp)
}

func GetAllCarsInner(ctx context.Context, c *app.RequestContext) (*car.GetAllCarsResp, error) {
	resp := new(car.GetAllCarsResp)
	cars, err := mysql.GetSingletonCarDAO().GetAllCars()
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return resp, err
	}
	resp.Cars = cars
	return resp, nil
}
